# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BTP Deployment

on:
  push:
    branches: [ "ghactions" ]
  pull_request:
    branches: [ "ghactions" ]

jobs:
  build:

    runs-on: Tutorial

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # remove here the 'cache: "npm" line (from a GitHub Template) if you don't want to use caching (takes a lot of time and space)
    - run: npm ci
    - name: Build 
      run: mbt build --mtar archive.mtar
    - name: Deploy to Cloud Foundry
      # Everything in ONE line. cf login and cf deploy commands are executed in the same step, so you must write ; between them.
      # This works also under Windows, Mac and Linux
      run: cf login -a ${{ secrets.CF_APIURL }} -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -o SUPORTIS_AG_demo-dev-psdpn57u -s dev; cf deploy mta_archives/archive.mtar
    - name: Push Message
      run: curl -d "Deployment finished" (ntfy-url)

